"""R ``twfeweights`` output-parity tests for the TWFE weight diagnostics.

Loads pre-computed golden values from
``benchmarks/data/twfeweights_golden.json`` (generated by
``benchmarks/R/generate_twfeweights_golden.R``) and asserts that the Python
implementation matches R ``twfeweights`` 0.9.0.

**R is only needed to regenerate the JSON**, never to run these tests. The
committed JSON plus its sibling panel CSVs are the source of truth and the
assertions run on any Python-only environment. Tests skip ONLY if a fixture
file is absent.

Tolerances are module constants with a stated rationale; see the tolerance
table in ``docs/methodology/REGISTRY.md`` under "TWFE Weight Diagnostics".
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import diff_diff
from diff_diff.twfe_weights import attgt_weights

DATA_DIR = Path(__file__).parents[1] / "benchmarks" / "data"
GOLDEN_PATH = DATA_DIR / "twfeweights_golden.json"
REGENERATE = "Rscript benchmarks/R/generate_twfeweights_golden.R"

FIXTURES = ("mpdta", "sim_staggered", "unbalanced_cohorts")
AGGREGATIONS = ("twfe", "overall", "simple")

# Closed-form weights: both sides evaluate the same rational expression in
# cohort masses in double precision, so only representation error separates
# them. Observed max deviation across all 3 fixtures x 3 aggregations is
# 4.7e-16 - two orders of margin below this gate.
WEIGHT_ATOL = 1e-12
WEIGHT_RTOL = 0.0

# Composed check: our CallawaySantAnna ATT(g,t) vs R did::att_gt, then the
# weights on top. Bounded by the pre-existing CS parity band, not by anything
# this module introduces.
CS_COMPOSED_RTOL = 1e-6


@pytest.fixture(scope="module")
def golden():
    """Load the committed R goldens; skip when absent."""
    if not GOLDEN_PATH.exists():
        pytest.skip(f"golden file not found at {GOLDEN_PATH}; run: {REGENERATE}")
    with open(GOLDEN_PATH) as fh:
        return json.load(fh)


def _fixture(golden, name):
    payload = golden["fixtures"][name]
    path = DATA_DIR / payload["data_file"]
    if not path.exists():
        pytest.skip(f"panel {path} not found; run: {REGENERATE}")
    return payload, pd.read_csv(path)


def _sorted_golden_weights(block):
    """Golden weight table, sorted to the same key order the API emits."""
    return (
        pd.DataFrame(
            {
                "group": block["group"],
                "time": block["time"],
                "post": block["post"],
                "weight": block["weight"],
                "att": block["att"],
            }
        )
        .sort_values(["group", "time"])
        .reset_index(drop=True)
    )


def _fit_cs(df, cols):
    return diff_diff.CallawaySantAnna(control_group="never_treated", base_period="universal").fit(
        df,
        outcome=cols["outcome"],
        unit=cols["unit"],
        time=cols["time"],
        first_treat=cols["first_treat"],
    )


class TestATTGTWeightsParity:
    """Weights asserted against R using R's OWN ATT(g,t) values.

    Feeding the golden ``att`` column back in isolates the weight arithmetic
    from CallawaySantAnna-vs-``did`` parity, which is covered separately by
    ``csdid_golden_values.json``. A regression here is a regression in THIS
    module.
    """

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_weight_column(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        expected = _sorted_golden_weights(payload["attgt_weights"][aggregation])

        gt_frame = expected[["group", "time", "att"]].rename(columns={"att": "effect"})
        cols = payload["columns"]
        result = attgt_weights(
            gt_frame,
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        actual = result.weights.sort_values(["group", "time"]).reset_index(drop=True)

        assert len(actual) == len(expected)
        np.testing.assert_array_equal(actual["group"].to_numpy(), expected["group"].to_numpy())
        np.testing.assert_array_equal(actual["time"].to_numpy(), expected["time"].to_numpy())
        np.testing.assert_array_equal(actual["post"].to_numpy(), expected["post"].to_numpy())
        np.testing.assert_allclose(
            actual["weight"].to_numpy(),
            expected["weight"].to_numpy(),
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_implied_att(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        block = payload["attgt_weights"][aggregation]
        expected = _sorted_golden_weights(block)
        cols = payload["columns"]

        result = attgt_weights(
            expected[["group", "time", "att"]].rename(columns={"att": "effect"}),
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        np.testing.assert_allclose(
            result.implied_att,
            block["implied_att"],
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )


class TestATTGTWeightsFromCSFit:
    """End-to-end: fit CallawaySantAnna, then weight its own ATT(g,t).

    This is a COMPOSED check - it multiplies this module's parity by
    CallawaySantAnna-vs-``did`` parity. It is deliberately looser than
    :class:`TestATTGTWeightsParity`, and a failure here with that class green
    points at CS, not at the weights.
    """

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_end_to_end(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        block = payload["attgt_weights"][aggregation]
        result = attgt_weights(_fit_cs(df, payload["columns"]), aggregation=aggregation)
        actual = result.weights.sort_values(["group", "time"]).reset_index(drop=True)
        expected = _sorted_golden_weights(block)

        np.testing.assert_allclose(
            actual["weight"].to_numpy(),
            expected["weight"].to_numpy(),
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )
        # ATT(g,t) come from our own fit here, so this leg carries the CS band.
        np.testing.assert_allclose(
            actual["att"].to_numpy(),
            expected["att"].to_numpy(),
            rtol=CS_COMPOSED_RTOL,
            atol=1e-9,
        )
        np.testing.assert_allclose(
            result.implied_att,
            block["implied_att"],
            rtol=CS_COMPOSED_RTOL,
            atol=1e-9,
        )

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_negative_weights_are_a_twfe_phenomenon(self, golden, fixture):
        """TWFE puts negative weight on some cells; the CS estimands never do."""
        payload, df = _fixture(golden, fixture)
        fit = _fit_cs(df, payload["columns"])

        twfe = attgt_weights(fit, aggregation="twfe")
        assert twfe.n_negative > 0
        assert twfe.negative_weight_share > 0

        for aggregation in ("overall", "simple"):
            benign = attgt_weights(fit, aggregation=aggregation)
            assert benign.n_negative == 0
            assert benign.negative_weight_share == 0.0

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_target_estimand_weights_sum_to_one(self, golden, fixture):
        """ATT^O and ATT^simple are proper averages of the post cells."""
        payload, df = _fixture(golden, fixture)
        fit = _fit_cs(df, payload["columns"])
        for aggregation in ("overall", "simple"):
            weights = attgt_weights(fit, aggregation=aggregation).weights
            np.testing.assert_allclose(weights["weight"].sum(), 1.0, atol=1e-12)


class TestCSFitAndFrameAgree:
    """The DataFrame fallback reproduces the fitted-result path exactly."""

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_paths_agree(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        fit = _fit_cs(df, cols)

        from_fit = attgt_weights(fit, aggregation=aggregation)
        from_frame = attgt_weights(
            fit.to_dataframe("group_time"),
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        left = from_fit.weights.sort_values(["group", "time"]).reset_index(drop=True)
        right = from_frame.weights.sort_values(["group", "time"]).reset_index(drop=True)
        np.testing.assert_allclose(
            left["weight"].to_numpy(), right["weight"].to_numpy(), atol=1e-15
        )
        np.testing.assert_allclose(from_fit.implied_att, from_frame.implied_att, atol=1e-15)
