"""R ``twfeweights`` output-parity tests for the TWFE weight diagnostics.

Loads pre-computed golden values from
``benchmarks/data/twfeweights_golden.json`` (generated by
``benchmarks/R/generate_twfeweights_golden.R``) and asserts that the Python
implementation matches R ``twfeweights`` 0.9.0.

**R is only needed to regenerate the JSON**, never to run these tests. The
committed JSON plus its sibling panel CSVs are the source of truth and the
assertions run on any Python-only environment. Tests skip ONLY if a fixture
file is absent.

Tolerances are module constants with a stated rationale; see the tolerance
table in ``docs/methodology/REGISTRY.md`` under "TWFE Weight Diagnostics".
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import diff_diff
from diff_diff.twfe_weights import attgt_weights

DATA_DIR = Path(__file__).parents[1] / "benchmarks" / "data"
GOLDEN_PATH = DATA_DIR / "twfeweights_golden.json"
REGENERATE = "Rscript benchmarks/R/generate_twfeweights_golden.R"

FIXTURES = ("mpdta", "sim_staggered", "unbalanced_cohorts")
AGGREGATIONS = ("twfe", "overall", "simple")

# Closed-form weights: both sides evaluate the same rational expression in
# cohort masses in double precision, so only representation error separates
# them. Observed max deviation across all 3 fixtures x 3 aggregations is
# 4.7e-16 - two orders of margin below this gate.
WEIGHT_ATOL = 1e-12
WEIGHT_RTOL = 0.0

# Composed check: our CallawaySantAnna ATT(g,t) vs R did::att_gt, then the
# weights on top. Bounded by the pre-existing CS parity band, not by anything
# this module introduces.
CS_COMPOSED_RTOL = 1e-6


@pytest.fixture(scope="module")
def golden():
    """Load the committed R goldens; skip when absent."""
    if not GOLDEN_PATH.exists():
        pytest.skip(f"golden file not found at {GOLDEN_PATH}; run: {REGENERATE}")
    with open(GOLDEN_PATH) as fh:
        return json.load(fh)


def _fixture(golden, name):
    payload = golden["fixtures"][name]
    path = DATA_DIR / payload["data_file"]
    if not path.exists():
        pytest.skip(f"panel {path} not found; run: {REGENERATE}")
    return payload, pd.read_csv(path)


def _sorted_golden_weights(block):
    """Golden weight table, sorted to the same key order the API emits."""
    return (
        pd.DataFrame(
            {
                "group": block["group"],
                "time": block["time"],
                "post": block["post"],
                "weight": block["weight"],
                "att": block["att"],
            }
        )
        .sort_values(["group", "time"])
        .reset_index(drop=True)
    )


def _fit_cs(df, cols):
    return diff_diff.CallawaySantAnna(control_group="never_treated", base_period="universal").fit(
        df,
        outcome=cols["outcome"],
        unit=cols["unit"],
        time=cols["time"],
        first_treat=cols["first_treat"],
    )


class TestATTGTWeightsParity:
    """Weights asserted against R using R's OWN ATT(g,t) values.

    Feeding the golden ``att`` column back in isolates the weight arithmetic
    from CallawaySantAnna-vs-``did`` parity, which is covered separately by
    ``csdid_golden_values.json``. A regression here is a regression in THIS
    module.
    """

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_weight_column(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        expected = _sorted_golden_weights(payload["attgt_weights"][aggregation])

        gt_frame = expected[["group", "time", "att"]].rename(columns={"att": "effect"})
        cols = payload["columns"]
        result = attgt_weights(
            gt_frame,
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        actual = result.weights.sort_values(["group", "time"]).reset_index(drop=True)

        assert len(actual) == len(expected)
        np.testing.assert_array_equal(actual["group"].to_numpy(), expected["group"].to_numpy())
        np.testing.assert_array_equal(actual["time"].to_numpy(), expected["time"].to_numpy())
        np.testing.assert_array_equal(actual["post"].to_numpy(), expected["post"].to_numpy())
        np.testing.assert_allclose(
            actual["weight"].to_numpy(),
            expected["weight"].to_numpy(),
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_implied_att(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        block = payload["attgt_weights"][aggregation]
        expected = _sorted_golden_weights(block)
        cols = payload["columns"]

        result = attgt_weights(
            expected[["group", "time", "att"]].rename(columns={"att": "effect"}),
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        np.testing.assert_allclose(
            result.implied_att,
            block["implied_att"],
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )


class TestATTGTWeightsFromCSFit:
    """End-to-end: fit CallawaySantAnna, then weight its own ATT(g,t).

    This is a COMPOSED check - it multiplies this module's parity by
    CallawaySantAnna-vs-``did`` parity. It is deliberately looser than
    :class:`TestATTGTWeightsParity`, and a failure here with that class green
    points at CS, not at the weights.
    """

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_end_to_end(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        block = payload["attgt_weights"][aggregation]
        result = attgt_weights(_fit_cs(df, payload["columns"]), aggregation=aggregation)
        actual = result.weights.sort_values(["group", "time"]).reset_index(drop=True)
        expected = _sorted_golden_weights(block)

        np.testing.assert_allclose(
            actual["weight"].to_numpy(),
            expected["weight"].to_numpy(),
            atol=WEIGHT_ATOL,
            rtol=WEIGHT_RTOL,
        )
        # ATT(g,t) come from our own fit here, so this leg carries the CS band.
        np.testing.assert_allclose(
            actual["att"].to_numpy(),
            expected["att"].to_numpy(),
            rtol=CS_COMPOSED_RTOL,
            atol=1e-9,
        )
        np.testing.assert_allclose(
            result.implied_att,
            block["implied_att"],
            rtol=CS_COMPOSED_RTOL,
            atol=1e-9,
        )

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_negative_weights_are_a_twfe_phenomenon(self, golden, fixture):
        """TWFE puts negative weight on some cells; the CS estimands never do."""
        payload, df = _fixture(golden, fixture)
        fit = _fit_cs(df, payload["columns"])

        twfe = attgt_weights(fit, aggregation="twfe")
        assert twfe.n_negative > 0
        assert twfe.negative_weight_share > 0

        for aggregation in ("overall", "simple"):
            benign = attgt_weights(fit, aggregation=aggregation)
            assert benign.n_negative == 0
            assert benign.negative_weight_share == 0.0

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_target_estimand_weights_sum_to_one(self, golden, fixture):
        """ATT^O and ATT^simple are proper averages of the post cells."""
        payload, df = _fixture(golden, fixture)
        fit = _fit_cs(df, payload["columns"])
        for aggregation in ("overall", "simple"):
            weights = attgt_weights(fit, aggregation=aggregation).weights
            np.testing.assert_allclose(weights["weight"].sum(), 1.0, atol=1e-12)


class TestCSFitAndFrameAgree:
    """The DataFrame fallback reproduces the fitted-result path exactly."""

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("aggregation", AGGREGATIONS)
    def test_paths_agree(self, golden, fixture, aggregation):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        fit = _fit_cs(df, cols)

        from_fit = attgt_weights(fit, aggregation=aggregation)
        from_frame = attgt_weights(
            fit.to_dataframe("group_time"),
            aggregation=aggregation,
            data=df,
            unit=cols["unit"],
            time=cols["time"],
            first_treat=cols["first_treat"],
        )
        left = from_fit.weights.sort_values(["group", "time"]).reset_index(drop=True)
        right = from_frame.weights.sort_values(["group", "time"]).reset_index(drop=True)
        np.testing.assert_allclose(
            left["weight"].to_numpy(), right["weight"].to_numpy(), atol=1e-15
        )
        np.testing.assert_allclose(from_fit.implied_att, from_frame.implied_att, atol=1e-15)


# FWL decomposition. R double-demeans with `fixest::demean`, an iterative
# alternating-projections solver with a 1e-8 fixed-point tolerance; ours is
# the exact closed form on a balanced panel. The gap is fixest's convergence
# slack, which then propagates through the OLS projection of Ddot on Xdot.
DEMEAN_ATOL = 1e-10
DEMEAN_COV_ATOL = 1e-8
BALANCE_ATOL = 1e-9

# Cells whose comparison-group implicit weights are constant AND average to
# zero: ATT(g,t) there is a 0/0 limit. We return the limit (the unweighted
# contrast, exact); R divides the rounding errors and lands ~1e-4 away. The
# weights on such cells cancel exactly in the aggregate, so `estimate` is
# unaffected - which is why the scalar assertions below stay at 1e-10 while
# the per-cell gate is relaxed only where the degeneracy is DETECTED, never
# by hard-coding a fixture or period.
DEGENERATE_CELL_ATOL = 5e-2

# R names balance rows `mean_<covariate>` (it averages each covariate over
# periods within unit first); we keep the covariate's own name.
R_BALANCE_COLUMNS = {
    "unweighted_covs_treated": "unweighted_treated",
    "unweighted_covs_comparison": "unweighted_control",
    "unweighted_diff": "unweighted_diff",
    "weighted_covs_treated": "weighted_treated",
    "weighted_covs_comparison": "weighted_control",
    "weighted_diff": "weighted_diff",
    "sd": "sd",
    "unweighted_log_ratio_sd_diff": "unweighted_log_ratio_sd",
    "weighted_log_ratio_sd_diff": "weighted_log_ratio_sd",
    "unweighted_frac_treated_extreme": "unweighted_frac_extreme",
    "weighted_frac_treated_extreme": "weighted_frac_extreme",
}


def _decompose(df, cols, **kwargs):
    return diff_diff.decompose_twfe_weights(
        df,
        outcome=cols["outcome"],
        unit=cols["unit"],
        time=cols["time"],
        first_treat=cols["first_treat"],
        **kwargs,
    )


def _degenerate_mask(cells, golden_cells):
    """Rows where R's ATT(g,t) is a 0/0 artifact rather than a disagreement.

    Detected from the DATA: a degenerate cell is one whose weight is exactly
    offset by another cell in the same period (they cancel in the aggregate),
    which is the signature of a vanishing comparison-group normalizer.
    """
    weights = np.asarray(golden_cells["weight"], dtype=float)
    times = np.asarray(golden_cells["time"], dtype=float)
    mask = np.zeros(len(weights), dtype=bool)
    for t in np.unique(times):
        in_period = times == t
        if in_period.sum() > 1 and abs(weights[in_period].sum()) < 1e-12:
            mask |= in_period
    return mask


class TestDecompositionParityFWL:
    """R ``implicit_twfe_weights`` parity, including the no-covariate branch."""

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_no_covariate_branch_two_ways(self, golden, fixture):
        """``covariates=None`` and a time-invariant covariate must agree.

        The golden was generated with ``xformula = ~<time-invariant col>``
        because upstream cannot run ``~1`` (``fixest::demean`` segfaults on
        the zero-column model matrix). Asserting BOTH Python calls against
        that single golden proves the equivalence instead of assuming it.
        """
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        expected = payload["decompose"]["fwl_nocov"]

        without = _decompose(df, cols, covariates=None)
        with pytest.warns(UserWarning, match="no within-unit-and-period variation"):
            with_invariant = _decompose(df, cols, covariates=[cols["invariant_cov"]])

        np.testing.assert_allclose(
            without.cells["weight"].to_numpy(),
            with_invariant.cells["weight"].to_numpy(),
            atol=1e-15,
        )
        assert without.estimate == pytest.approx(with_invariant.estimate, abs=1e-15)

        for result in (without, with_invariant):
            np.testing.assert_allclose(result.estimate, expected["estimate"], atol=DEMEAN_ATOL)
            np.testing.assert_allclose(
                result.cells["weight"].to_numpy(),
                np.asarray(expected["cells"]["weight"]),
                atol=DEMEAN_ATOL,
            )

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("key", ["fwl_nocov", "fwl_cov", "fwl_gmin1"])
    def test_scalars(self, golden, fixture, key):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        expected = payload["decompose"][key]
        kwargs = {
            "fwl_nocov": {"covariates": None},
            "fwl_cov": {"covariates": [cols["varying_cov"]]},
            "fwl_gmin1": {"covariates": None, "base_period": "gmin1"},
        }[key]
        atol = DEMEAN_COV_ATOL if key == "fwl_cov" else DEMEAN_ATOL

        result = _decompose(df, cols, **kwargs)

        # `estimate` is invariant to the 0/0 cells - the weights on them
        # cancel - so it is gated tightly on EVERY fixture. The
        # decomposition/remainder SPLIT is not invariant: under gmin1 the
        # remainder is itself built from the degenerate comparison-group
        # weights, so R's noise moves mass between the two halves while
        # leaving their sum exact.
        np.testing.assert_allclose(result.estimate, expected["estimate"], atol=atol)

        split_atol = atol
        if _degenerate_mask(result.cells, expected["cells"]).any():
            split_atol = DEGENERATE_CELL_ATOL
        for field in ("decomposition", "remainder"):
            np.testing.assert_allclose(getattr(result, field), expected[field], atol=split_atol)

        # estimate == decomposition + remainder is an identity, not a fit
        assert result.estimate == pytest.approx(result.decomposition + result.remainder, abs=1e-12)

    @pytest.mark.parametrize("fixture", FIXTURES)
    @pytest.mark.parametrize("key", ["fwl_nocov", "fwl_cov"])
    def test_cells(self, golden, fixture, key):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        expected = payload["decompose"][key]
        kwargs = {
            "fwl_nocov": {"covariates": None},
            "fwl_cov": {"covariates": [cols["varying_cov"]]},
        }[key]
        atol = DEMEAN_COV_ATOL if key == "fwl_cov" else DEMEAN_ATOL

        result = _decompose(df, cols, **kwargs)
        np.testing.assert_allclose(
            result.cells["weight"].to_numpy(),
            np.asarray(expected["cells"]["weight"]),
            atol=atol,
        )

        actual_att = result.cells["att"].to_numpy()
        golden_att = np.asarray(expected["cells"]["att"])
        degenerate = _degenerate_mask(result.cells, expected["cells"])
        np.testing.assert_allclose(actual_att[~degenerate], golden_att[~degenerate], atol=atol)
        if degenerate.any():
            np.testing.assert_allclose(
                actual_att[degenerate],
                golden_att[degenerate],
                atol=DEGENERATE_CELL_ATOL,
            )


class TestDecompositionIsExactAtDegenerateCells:
    """Where R reports 0/0 noise, we report the analytic limit."""

    def test_limit_equals_the_unweighted_contrast(self, golden):
        """sim_staggered has three equal cohorts, so E_3[D] == mean_t E_t[D].

        The comparison-group implicit weights are then constant and average to
        zero. The limit of ``resid / mean(resid)`` for a constant vector is
        one, so ATT(g, 3) is the plain difference of mean outcome changes -
        computable here without any of the module's machinery.
        """
        payload, df = _fixture(golden, "sim_staggered")
        cols = payload["columns"]
        result = _decompose(df, cols, covariates=None)

        wide = df.pivot(index=cols["unit"], columns=cols["time"], values=cols["outcome"]).to_numpy()
        cohorts = df.groupby(cols["unit"])[cols["first_treat"]].first().to_numpy()
        change = wide[:, 2] - wide[:, 0]  # base_period="first_period"
        control_mean = change[cohorts == 0].mean()

        for cohort in (3, 4):
            expected = change[cohorts == cohort].mean() - control_mean
            actual = result.cells.query("group == @cohort and time == 3")["att"]
            assert actual.iloc[0] == pytest.approx(expected, abs=1e-12)

    def test_warns_about_the_degenerate_cells(self, golden):
        payload, df = _fixture(golden, "sim_staggered")
        with pytest.warns(UserWarning, match="0/0 limit"):
            _decompose(df, payload["columns"], covariates=None)


class TestBalanceParity:
    """R ``twfe_cov_bal`` + ``mp_covariate_bal_summary_helper`` parity."""

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_cell_level(self, golden, fixture):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        expected = pd.DataFrame(payload["balance"]["fwl"]["cells"])
        expected["covariate"] = expected["covariate"].str.replace("^mean_", "", regex=True)

        result = _decompose(
            df,
            cols,
            covariates=[cols["varying_cov"]],
            balance_covariates=[cols["invariant_cov"], cols["varying_cov"]],
        )
        actual = result.covariate_balance(level="cell", standardize=False)

        key = ["group", "time", "covariate"]
        expected = expected.sort_values(key).reset_index(drop=True)
        actual = actual.sort_values(key).reset_index(drop=True)
        assert actual["covariate"].tolist() == expected["covariate"].tolist()

        for r_name, our_name in R_BALANCE_COLUMNS.items():
            np.testing.assert_allclose(
                actual[our_name].to_numpy(dtype=float),
                expected[r_name].to_numpy(dtype=float),
                atol=BALANCE_ATOL,
                err_msg=f"balance column {our_name!r} ({fixture})",
            )

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_summary_level(self, golden, fixture):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]
        expected = pd.DataFrame(payload["balance"]["fwl"]["summary"])
        expected["covariate"] = expected["covariate"].str.replace("^mean_", "", regex=True)

        result = _decompose(
            df,
            cols,
            covariates=[cols["varying_cov"]],
            balance_covariates=[cols["invariant_cov"], cols["varying_cov"]],
        )
        actual = result.covariate_balance(level="summary", standardize=False)

        expected = expected.sort_values("covariate").reset_index(drop=True)
        actual = actual.sort_values("covariate").reset_index(drop=True)
        assert actual["covariate"].tolist() == expected["covariate"].tolist()

        r_summary = {
            "unweighted_treat": "unweighted_treated",
            "unweighted_untreat": "unweighted_control",
            "unweighted_diff": "unweighted_diff",
            "weighted_treat": "weighted_treated",
            "weighted_untreat": "weighted_control",
            "weighted_diff": "weighted_diff",
            "sd": "sd",
            "unweighted_log_ratio_sd_diff": "unweighted_log_ratio_sd",
            "weighted_log_ratio_sd_diff": "weighted_log_ratio_sd",
            "unweighted_frac_treated_extreme": "unweighted_frac_extreme",
            "weighted_frac_treated_extreme": "weighted_frac_extreme",
        }
        for r_name, our_name in r_summary.items():
            np.testing.assert_allclose(
                actual[our_name].to_numpy(dtype=float),
                expected[r_name].to_numpy(dtype=float),
                atol=BALANCE_ATOL,
                err_msg=f"balance summary {our_name!r} ({fixture})",
            )


class TestCrossSurfaceIdentity:
    """attgt_weights and decompose_twfe_weights describe the same regression."""

    @pytest.mark.parametrize("fixture", FIXTURES)
    def test_twfe_weights_reproduce_the_decomposition(self, golden, fixture):
        payload, df = _fixture(golden, fixture)
        cols = payload["columns"]

        weighted = attgt_weights(_fit_cs(df, cols), aggregation="twfe")
        decomposed = _decompose(df, cols, covariates=None)

        assert weighted.implied_att == pytest.approx(decomposed.estimate, abs=1e-6)
